run:
  timeout: 10m

  skip-files:
    - ".*_test.go$"
  skip-dirs:
    - "v1175"

linters:
  enable:
    - asciicheck
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gci
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - revive
    - wastedassign
issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G108:"
    - linters:
        - govet
      text: "sigchanyzer: misuse of unbuffered os.Signal channel as argument to signal.Notify"
    - linters:
        - staticcheck
      text: "SA1017:"
    - linters:
        - revive
      text: "exported: type name will be used as collector.CollectorConfig by other packages,"
    - linters:
        - revive
      text: "blank-imports: a blank import should be only in a main or test package"
