name: Server-Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  server-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
          args: --verbose

