name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server-test:
    strategy:
      matrix:
        dbversion: ['mysql:5.7']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    services:
      mysql:
        image: ${{ matrix.dbversion }}
        env:
          MYSQL_DATABASE: final
          MYSQL_USER: final
          MYSQL_PASSWORD: final
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        ports:
          - 9910:3306
        options: >-
          --health-cmd "mysqladmin ping -ufinal -pfinal"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo os
        run: |
          echo ${{runner.os}}

      - name: Test
        run: |
          export MYSQL_CONN_STR="final:final@tcp(localhost:9910)/final?charset=utf8&parseTime=True"
          export AMQP_CONN_STR="${{ secrets.AMQPCONNSTR }}"
          make test

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
          flags: unittests
          name: codecov-umbrella


